### ISSUE TITLE
Show state in data columns

### ISSUE THREAD

**Issue by claha** [gwendo/entities-table-card#1]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to show the current state in the table.

**Describe the solution you'd like**
To be able to show the state in a colum.

**Describe alternatives you've considered**
For my personal use case I could (since I am the developer) update avanza_stock to have an attribute that corresponds to the state. But if this is to be used by other components that might not be an option.

**Comment by gwendo** [comment]
@claha Would something like this work: 

``` yaml
type: 'custom:entities-table-card'
name: Portfolio
entities:
  - entity: sensor.avanza_stock_513577
  - entity: sensor.avanza_stock_26607
  - entity: sensor.avanza_stock_5247
dataColumns:
  - header: Name
    attr: name
  - header: State
    source: state
    format: number
  - header: '%'
    attr: profitLossPercentage
    format: percentage
  - header: Profit/Loss
    attr: totalProfitLoss
    format: currency
    showSummary: true
  - header: Value
    attr: totalValue
    format: currency
    showSummary: true

```

I have introduced source as an attribute for the dataColumn which defaults to attr but you can set it to state to get the state. 
I also moved the showSummary down to the individual dataColumn it will still only apply to currency format data columns.
